# Generated by Django 4.2.21 on 2025-05-23 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('objective_type', models.CharField(choices=[('max', 'Maximiser'), ('min', 'Minimiser')], max_length=10)),
                ('objective_function', models.TextField()),
                ('constraints', models.JSONField(default=list)),
                ('num_variables', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='imported_problems/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problème',
                'verbose_name_plural': 'Problèmes',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ImportedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imported_problems/')),
                ('original_text', models.TextField(blank=True)),
                ('extracted_objective_type', models.CharField(default='min', max_length=10)),
                ('extracted_objective', models.TextField(blank=True)),
                ('extracted_constraints', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
