# Generated by Django 4.2.21 on 2025-05-15 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('objective_type', models.CharField(choices=[('max', 'Maximisation'), ('min', 'Minimisation')], default='max', max_length=3)),
                ('objective_coefficients', models.JSONField()),
                ('constraints', models.JSONField()),
                ('num_variables', models.IntegerField()),
                ('import_file', models.FileField(blank=True, null=True, upload_to='problem_imports/')),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
