# Generated by Django 4.2.17 on 2025-05-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
    ]
