# Generated by Django 4.2.21 on 2025-05-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedproblem',
            options={'verbose_name': 'Problème importé', 'verbose_name_plural': 'Problèmes importés'},
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='extracted_constraints',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='extracted_objective',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='extracted_objective_type',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='original_text',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_imported',
        ),
        migrations.AddField(
            model_name='importedproblem',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas d'échec du traitement", null=True),
        ),
        migrations.AddField(
            model_name='importedproblem',
            name='problem_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='problems.problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedproblem',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedproblem',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importedproblem',
            name='file',
            field=models.FileField(help_text='Fichier PDF ou image contenant le problème', upload_to='imported_problems/'),
        ),
        migrations.AlterField(
            model_name='importedproblem',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
