# Generated by Django 4.2.21 on 2025-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-date_created'], 'verbose_name': 'Problème', 'verbose_name_plural': 'Problèmes'},
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='optimal_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='tableaus_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='variable_names',
            field=models.JSONField(default=list),
        ),
    ]
