# Generated by Django 4.2.21 on 2025-05-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_importedproblem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproblem',
            name='constraints_I',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='importedproblem',
            name='objective_coefficients_I',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='importedproblem',
            name='objective_type_I',
            field=models.CharField(choices=[('max', 'Maximisation'), ('min', 'Minimisation')], max_length=3, null=True),
        ),
    ]
