# Generated by Django 4.2.21 on 2025-05-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_options_problem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
    ]
