# Generated by Django 4.2.21 on 2025-05-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_importedproblem_constraints_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedproblem',
            name='constraints_I',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='objective_coefficients_I',
        ),
        migrations.RemoveField(
            model_name='importedproblem',
            name='objective_type_I',
        ),
        migrations.AddField(
            model_name='problem',
            name='objective_coefficients',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
