# Generated by Django 4.2.21 on 2025-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints_equation_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='objective_equation_str',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
