# Generated by Django 4.2.21 on 2025-05-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_importedproblem_constraints_i_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='objective_coefficients',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='objective_function',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='objective_type',
            field=models.CharField(blank=True, choices=[('max', 'Maximiser'), ('min', 'Minimiser')], max_length=10),
        ),
    ]
