# Generated by Django 4.2.21 on 2025-05-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_constraints_equation_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='variable_names',
            field=models.JSONField(default=list),
        ),
    ]
