# Generated by Django 4.2.21 on 2025-05-24 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0008_problem_variable_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedproblem',
            old_name='status',
            new_name='statusForImport',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='objective_function',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='original_file',
        ),
        migrations.AddField(
            model_name='problem',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='optimal_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_variables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='tableaus_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='num_variables',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='objective_coefficients',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='objective_type',
            field=models.CharField(choices=[('max', 'Maximisation'), ('min', 'Minimisation')], default='max', max_length=3),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
