# Generated by Django 4.2.21 on 2025-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_rename_status_importedproblem_statusforimport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='num_variables',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
