# Generated by Django 4.2.21 on 2025-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problem_num_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='objective_coefficients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='variable_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
